color:
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  brandStrength: 0.3566513687837869
  lightness: 0.4831749920267612
  saturation: 0.6452103576157242
  rhythmicContrast: 0.1364653492346406
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: akashicflow.io
layout_spectrum: 0.5298904834780842
typography_spectrum: 0.7185394279658794
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=http%3A%2F%2Fwww.youtube.com%2Fembed%2FRtU_mdL2vBM&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DRtU_mdL2vBM&image=http%3A%2F%2Fi.ytimg.com%2Fvi%2FRtU_mdL2vBM%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - avatar: {}
      related: []
      publisher:
        url: 'http://youtube.com'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
        domain: www.youtube.com
      keywords:
        - nasa live
        - live space
        - earth from space
        - live
        - earth
        - space
        - nasa
        - space video
        - iss live
        - iss live stream
        - iss live feed
        - space station
        - iss
        - nasa video
        - spa...
      description: >-
        Live (2018) NASA Earth from Space - "International Astronomy Day", ISS
        HD Video is presented. NASA Live stream of Earth seen from space powered
        by NASA HDEV cameras aboard the International Space Station. Watch the
        Earth roll Captured by HDEV cameras on board the International Space
        Station.
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=RtU_mdL2vBM&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=RtU_mdL2vBM&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=RtU_mdL2vBM&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=RtU_mdL2vBM&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=RtU_mdL2vBM&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=RtU_mdL2vBM'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=RtU_mdL2vBM
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=RtU_mdL2vBM
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://www.youtube.com/watch?v=RtU_mdL2vBM'
      title: >-
        NASA Live - Earth From Space (HDVR) ♥ ISS LIVE FEED #AstronomyDay2018 |
        Subscribe now!
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
url: 'https://thegrid.ai/akashicflow/'
title: Let's Make this Happen!
description: We are the shit!
